# Site settings
title: Il cinema come amuleto
description: Alcune osservazioni sui cinema africano e terzo cinema
logo: /assets/img/logo.webp
timezone: Europe/Rome
paginate: 6
words_per_minute: 200

# Author settings
author: Simona Cella
author-pic: /assets/img/Myself.jpeg
about-author: Scriptwriter, Producer, Film Critic 
about-author-long: |
  Esperta di cinema africano e terzo cinema, dopo una lunga esperienza nel mondo della produzione
  cinematografica e dell’organizzazione culturale, si è specializzata nello sviluppo e nella curatela
  di progetti di cinema espanso inteso come processo multidisciplinare che accompagna la produzione di
  un film attivando progetti artistici paralleli in un’ottica di valorizzazione e rigenerazione culturale del territorio. 
 
  E' autrice di sceneggiature e scrive di cinema per Nigrizia e Africa & Mediterraneo. 
  
  Ha curato insieme a Cinzia Quadrati la monografia "Djibril Diop Mambety o il viaggio della Iena", 
  con prefazione di Martin Scorsese, pubblicato in Italia e Francia da Editions L'Harmattan.

  Collabora con artisti, registi, collettivi, associazioni culturali, produzioni cinematografiche,
  istituzioni culturali, scuole ed università. 
  
# Contact links
email: simona.reichmann@gmail.com
website: https://simonacella.github.io
linkedin: simona-cella-a531b4b/
github:  simonacella
facebook: simona.cella.9
instagram: simona_reichmann
imdb: nm7677685


### Do not change the settings below unless you know what you are doing ###

# Build settings
baseurl: /
paginate_path: 'page:num'
permalink: :title:output_ext
url: https://simonacella.github.io
markdown: kramdown
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

category_archive:
  type: liquid
  path: /categories/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-youtube

include: [_pages]
