# Site settings
title: Simona Cella
description: 'Scriptwriter, Producer, Film Critic'
permalink: ':title:output_ext'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://simonacella.github.io"
logo: "/assets/img/branding/MVM-logo-full.svg"
logo-icon: "/assets/img/branding/MVM-symbol.svg"
logo-icon-SEO: "/assets/img/branding/MVM-symbol-black.png" # must be a non SVG file

highlight_theme: syntax-base16.monokai.dark # select a dark theme for the code highlighter if needed

# Author settings
author: Simona Cella
author-pic: Myself.jpeg
about-author: Scriptwriter, Producer, Film Critic 

# Contact links
email: simona.reichmann@gmail.com
phone: # Add your Phone number
website: https://simonacella.github.io
linkedin: simona-cella-a531b4b/
github:  # Add your Github handle
twitter:  # Add your Twitter handle
bandcamp:  # Add your Bandcamp username
stackoverflow:  # Add your stackoverflow account
facebook: simona.cella.9
instagram: simona_reichmann

# Newsletter
mailchimp: # mailchimp newsletter

# Paginate
paginate: 6
paginate_path: 'page:num'
words_per_minute: 200

# Comments
comments: #[disqus, utteranc]
comments_opts:
  comments_curtain: yes # leave empty to show the disqus embed directly
  repo: # The GitHub repo URL.  https://utteranc.es/
  issue_term: # The GitHub issue label
  label: # The GitHub comments label
  theme: # The GitHub comment's there. e.g. github-dark
  # Disqus
  discus_identifier: # Add your discus identifier

# Build settings
markdown: kramdown
mathjax: true
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Outputting
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

category_archive:
  type: liquid
  path: /categories/

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
