# Site settings
title: Simona Cella
description: Scriptwriter, Producer, Film Critic
permalink: :title:output_ext
baseurl: /
url: https://simonacella.github.io

# Author settings
author: Simona Cella
author-pic: Myself.jpeg
about-author: Scriptwriter, Producer, Film Critic 

# Contact links
email: simona.reichmann@gmail.com
phone:
website: https://simonacella.github.io
linkedin: simona-cella-a531b4b/
github:  simonacella
facebook: simona.cella.9
instagram: simona_reichmann
imdb: nm7677685

# Paginate
paginate: 6
paginate_path: 'page:num'
words_per_minute: 200

# Build settings
markdown: kramdown
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

timezone: Europe/Rome

category_archive:
  type: liquid
  path: /categories/

plugins:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
